#cloud-config
runcmd:
  - sudo yum update -y
  - sudo amazon-linux-extras install docker
  - sudo usermod -a -G docker ec2-user
  - sudo systemctl start docker.service
  - sudo systemctl enable docker.service
  - docker run --restart always -P -d -p 80:80 nginxdemos/hello:plain-text

